hashtag_media = ['g1', 'uolentrevista', 'globonews', 'uolnews', 'portalig', 'news',
       'bot', 'panfleterobot', 'jornaldacultura', 'jn', 'aprizion',
       'breakingnews', 'breaking_news', 'odia', 'noarnacbn',
       'canaisglobo', 'aovivo', 'urgente', 'política', 'politica',
       'bandjornalismo', 'notíciaatual', 'rodaviva', 'uol', 'msnbrasil',
       'nexoexpresso', 'r7', 'noticias', 'conexaoglobonews', 'estudioi',
       'meme', 'exclusivo', 'informação', 'jornalismo', 'edicao18',
       'notícia', '15minutosgazetadopovo', 'rádiopampa', 'jornaldarecord',
       'novodia', 'pnbonline', 'cnn', 'rádio', 'jornaldagazeta',
       'faroldabahia', 'factchecking', 'blogtuliolemos',
       'conexãoglobonews', 'ariquemesonline', 'tuneinbrasil', 'bnews',
       'notícias', 'opopular', 'JornalDaRecord', 'JR24H', 'GloboNews',
       'Edicao16', 'oFuxiqueiro', 'JornalNacional', 'jornalnacional',
       'JN', 'EmPauta', 'G1', 'JG', 'Jn', 'Bandnewsfm', 'JornaldaRecord',
       'CnnBrasil', 'UOLDebate', 'UOLEntrevista', 'RodaViva', 'UOLNews',
       '3em1', 'BBB21', 'CapaDoDia', 'BBB101', 'Fantástico', 'fantastico',
       'Aprizion', 'Fantastico', 'OpiniaoNoAr', 'Edicao18', 'RedePampa',
       'jornalpiracicabano', 'braincast', 'BREAKING', 'ManhãBandeirantes',
       'CopaAmericaNoSBT', 'GNewsEmPonto', 'OlimpiadasNaGlobo',
       'FatosDaSemana', 'Coluna', 'shorts', 'PrimeiroCafe', 'TênisNaESPN',
       'DF1', 'J10', 'PapodePolítica', 'ConversaComBiaEMau', 'podcast',
       'infojurid', 'conjur', 'RedeTVT', 'ficaadica']